-- Gold Tracker - Extended Gold Types Schema
-- Add new gold types to support all current gold data

-- Add new columns for extended gold types
ALTER TABLE gold_prices 
ADD COLUMN IF NOT EXISTS full_gold_buy DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS full_gold_sell DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS full_gold_change_percent DECIMAL(5,2) DEFAULT 0,

ADD COLUMN IF NOT EXISTS cumhuriyet_gold_buy DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cumhuriyet_gold_sell DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cumhuriyet_gold_change_percent DECIMAL(5,2) DEFAULT 0,

ADD COLUMN IF NOT EXISTS ata_gold_buy DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS ata_gold_sell DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS ata_gold_change_percent DECIMAL(5,2) DEFAULT 0,

ADD COLUMN IF NOT EXISTS ikibuçuk_gold_buy DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS ikibuçuk_gold_sell DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS ikibuçuk_gold_change_percent DECIMAL(5,2) DEFAULT 0,

ADD COLUMN IF NOT EXISTS beşli_gold_buy DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS beşli_gold_sell DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS beşli_gold_change_percent DECIMAL(5,2) DEFAULT 0,

ADD COLUMN IF NOT EXISTS bilezik_14_buy DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS bilezik_14_sell DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS bilezik_14_change_percent DECIMAL(5,2) DEFAULT 0,

ADD COLUMN IF NOT EXISTS bilezik_18_buy DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS bilezik_18_sell DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS bilezik_18_change_percent DECIMAL(5,2) DEFAULT 0,

ADD COLUMN IF NOT EXISTS bilezik_22_buy DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS bilezik_22_sell DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS bilezik_22_change_percent DECIMAL(5,2) DEFAULT 0,

ADD COLUMN IF NOT EXISTS gram_has_gold_buy DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS gram_has_gold_sell DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS gram_has_gold_change_percent DECIMAL(5,2) DEFAULT 0,

ADD COLUMN IF NOT EXISTS usd_try_buy DECIMAL(10,4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS usd_try_sell DECIMAL(10,4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS usd_try_change_percent DECIMAL(5,2) DEFAULT 0;
